#!/bin/bash -l 


# Ensure current directory is set
cd /home/iperez/projects/flpz || exit

# FLPZ Energy Program
# Executes the FLPZ (Flexoelectric Piezoelectric) energy calculations

# Usage: sbatch flpzEnergy.sh <input_file> <smodes_input> <irrep>

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <input_file> <smodes_input> <irrep>"
    exit 1
fi

echo "Beginning FLPZ Energy Program"

# Read input files and calculate constant quantities
input_file="$1"
smodes_input="$2"
irrep="$3"

general_structure_file=$(grep "genstruc" "$input_file" | awk '{print $2}')
structure=$(grep "name" "$input_file" | awk '{print $2}')
ntypat=$(grep "ntypat" "$general_structure_file" | awk '{print $2}')
bScriptPreamble=$(grep "sbatch_preamble" "$input_file" | awk '{print $2}')

# Create new working directory
dir="${structure}_${irrep}_Energy"
mkdir -p "$dir"

# Copy necessary files to working directory
handle_files() {
    local source_dir="$1"
    if [ "$2" = "cp" ]; then
        local files=(
            "shared/boilerplate_generation.sh"
            "shared/smodes_symmadapt_abinit.py"
            "shared/loop_smodes.tcsh"
            "shared/smodes_postproc_abinit.py"
            "energy/eigVecExtEnergy.sh"
            "energy/datapointCalcofEnergy.sh"
            "energy/dataAnalysisEnergy.sh"
            "shared/xredToxcart.sh"
	        "shared/xcartToxred.sh"
            "shared/findAngle.py"
            "shared/findSpaceGroup.sh"
	        "shared/xCartxRed.py"
        )
    elif [ "$2" = "rm" ]; then  
	local files=(
            "boilerplate_generation.sh"
            "smodes_symmadapt_abinit.py"
            "loop_smodes.tcsh"
            "smodes_postproc_abinit.py"
            "eigVecExtEnergy.sh"
            "datapointCalcofEnergy.sh"
            "dataAnalysisEnergy.sh"
            "xredToxcart.sh"
	        "xcartToxred.sh"
            "findAngle.py"
            "findSpaceGroup.sh"
	        "xCartxRed.py"
        )
    fi 
    for file in "${files[@]}"; do
        if [ "$2" = "rm" ]; then
            rm "$source_dir/$file"
        elif [ "$2" = "cp" ]; then
            cp "$source_dir/$file" "$dir/"
        fi
    done
}

handle_files "flpz_code" "cp"

# Copy input files into directory 
cp "$input_file" "$dir/"
cp "$smodes_input" "$dir/"
cp "$bScriptPreamble" "$dir/"

# Generate boilerplate
bash "$dir/boilerplate_generation.sh" "$input_file"
mv boilerplate "$dir"

# Change to working directory
cd "$dir" || exit

# Process smodes and FCEvecs
python3 smodes_symmadapt_abinit.py "$smodes_input" "$irrep"
tcsh loop_smodes.tcsh "$irrep"

# Copy pseudopotentials
copy_pseudos() {
    local dest_dir=$1
    for i in $(seq 2 $((ntypat + 1))); do
        pseudos=$(grep "pseudos" "../$general_structure_file" | awk "{print \$$i}" | sed 's/[,"]//g')
        cp "boilerplate/$pseudos" "$dest_dir/"
    done
}

copy_pseudos "SMODES_$irrep"
copy_pseudos "."

echo "Successfully created dependencies"
echo "FCEvecs calculations begin"

# Wait for jobs to finish 
job_ids=()
file_path=joblist

count=0
while IFS= read -r 
do
    cd "SMODES_${irrep}/dist_${count}" || exit
    # Submit job and capture the job ID
    job_id=$(sbatch jobscript.sh | awk '{print $4}')
    job_ids+=("$job_id")
    echo "Submitted batch job $job_id"
    cd - || exit
    count=$(( count + 1 ))
done < "$file_path"

# Wait for all jobs to finish
for job_id in "${job_ids[@]}"; do
    squeue -h -j "$job_id"
    while [ $? -eq 0 ]; do
        sleep 60  # Check every minute
        squeue -h -j "$job_id"
    done
    echo "Job $job_id completed"
done

echo "All batch scripts have completed"
echo "Post-processing of FCEvecs begins"

# Post-processing of FCEvecs

# Reassign SMODES as the genstruc file
sed -i "s|^genstruc .*|genstruc SMODES_${irrep}/dist_0/dist_0.abi|" "$input_file"
general_structure_file=$(grep "genstruc" "$input_file" | awk '{print $2}')

# Allows us to verify the space group of the unperturbed cell
bash xcartToxred.sh "$general_structure_file"
echo "The space group of the unperturbed cell is $(bash findSpaceGroup.sh "$general_structure_file")"

# Allows us to check and ensure that the conversion was correct
echo "#####################################################"
echo "General structure file pre-conversion"
cat "SMODES_${irrep}/dist_0/dist_0.abi"

bash xredToxcart.sh "SMODES_${irrep}/dist_0/dist_0.abi"

echo "#####################################################"
echo "General structure file post-conversion"
cat "SMODES_${irrep}/dist_0/dist_0.abi"
echo "#####################################################"

python3 smodes_postproc_abinit.py "$irrep"
mv "SMODES_${irrep}/FCEvecs.dat" "."
mv "SMODES_${irrep}/DynFreqs.dat" "."

# Allows user to view output of Prof. Ritz's program
echo "#####################################################"
echo "Printing FCEvecs.dat"
cat "FCEvecs.dat"
echo "#####################################################"
echo "Printing DynFreqs.dat"
cat "DynFreqs.dat"
echo "#####################################################"

bash eigVecExtEnergy.sh "DynFreqs.dat" "FCEvecs.dat" "$input_file"

eigVec_nlines=$(grep "eigVec_nlines" "$input_file" | awk '{print $2}')
mode_location=$(grep -n "eigVec_lines" "$input_file" | cut -d: -f1)
eigVec_lines=$(sed -n "$((mode_location+1)),$((mode_location+eigVec_nlines))p" "$input_file")

echo "Post-processing of FCEvecs is complete"
echo "Calculation of datapoints begins"

# Calculate datapoints
mkdir datapointInputFiles
for eigVec in $eigVec_lines; do
    bash datapointCalcofEnergy.sh "${input_file}_vec${eigVec}" 
    mv "${input_file}_vec${eigVec}" datapointInputFiles
done

rm "${structure}_*_vec*"
handle_files "." "rm"

#rm -r "boilerplate" "SMODES_${irrep}"

echo "FLPZ Program has completed calculations"
